- name: Create ALB
  community.aws.elb_application_lb:
    name: "{{ project_name }}-alb"
    state: present
    security_groups:
      - "{{ alb_sg.group_id }}"
    subnets: "{{ public_subnet_output.results | map(attribute='subnet.id') | list }}"
    region: "{{ aws_region }}"
  register: alb
