- name: Create ALB Security Group
  amazon.aws.ec2_security_group:
    name: "{{ project_name }}-alb-sg"
    description: ALB Security Group
    vpc_id: "{{ vpc.vpc.id }}"
    rules:
      - proto: tcp
        ports:
          - 80
          - 443
        cidr_ip: 0.0.0.0/0
    region: "{{ aws_region }}"
  register: alb_sg

- name: Create ECS Security Group
  amazon.aws.ec2_security_group:
    name: "{{ project_name }}-ecs-sg"
    description: ECS Security Group
    vpc_id: "{{ vpc.vpc.id }}"
    rules:
      - proto: tcp
        ports:
          - 8000
        group_id: "{{ alb_sg.group_id }}"
    region: "{{ aws_region }}"
  register: ecs_sg
